### ISSUE TITLE
McCafee detects .exe files and the files in "data" as a threat

### ISSUE THREAD

**Issue by JaxNanGaming** [AthenaADP/MH4U-ASS#1]
There is a problem with this in the direct version.

Also, how do I download this code and make it into .exe program?

**Comment by AthenaADP** [comment]
From the main project page (https://github.com/AthenaADP/MH4U-ASS) you should be able to click the green "Clone or download" button to download the source. You will need Visual Studio 2017 probably to compile it yourself.

I will submit the .exe for whitelisting in the meantime.

Thanks!
